**E-commerce preprocessing**

**I need to Access Data On Drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:


import gdown

file_id = "1pdlY-Q_dPrc9MEO10gsZiizFrBqA_QPu"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "data.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1pdlY-Q_dPrc9MEO10gsZiizFrBqA_QPu
To: /content/data.csv
100%|██████████| 2.29M/2.29M [00:00<00:00, 241MB/s]

'data.csv'

In [15]:
import os

os.listdir()

['.config', 'data.csv', 'drive', 'sample_data']

In [18]:
import pandas as pd

df = pd.read_csv("data.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

**Data Exploaration**

In [19]:
df.shape

(9994, 21)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [33]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Shipping Time,Profit Margin,Year,Month
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,3.958175,0.120314,2015.722233,7.809686
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000,-2.750000,2014.000000,1.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,3.000000,0.075000,2015.000000,5.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,4.000000,0.270000,2016.000000,9.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,5.000000,0.362500,2017.000000,11.000000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,7.000000,0.500000,2017.000000,12.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.747567,0.466754,1.123555,3.284654

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

**There is no Duplicates and no null values**

In [25]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [27]:
type("order Date")

str

**We should convert date from String to Datetime**

In [26]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

**Feature Engineering**

**Extract Shipping Time by this equation**

In [30]:
df['Shipping Time'] = (df['Ship Date'] - df['Order Date']).dt.days

**We calculate profit Margin**

In [31]:
df['Profit Margin'] = df['Profit'] / df['Sales']

**Extract years and Months from Date **

In [32]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month

**We should treat the outliers**

In [47]:
df[['Sales', 'Profit', 'Discount']].dtypes

Sales       float64
Profit      float64
Discount    float64
dtype: object

In [34]:
df[['Sales','Profit','Discount']].describe()

              Sales       Profit     Discount
count   9994.000000  9994.000000  9994.000000
mean     229.858001    28.656896     0.156203
std      623.245101   234.260108     0.206452
min        0.444000 -6599.978000     0.000000
25%       17.280000     1.728750     0.000000
50%       54.490000     8.666500     0.200000
75%      209.940000    29.364000     0.200000
max    22638.480000  8399.976000     0.800000

**Discount is unbalanced as minimum is 15% and maximum 75% so I think maximum discount can lead to the big loss in Profit**

**Profit I notice that there is big damage or big loss and at the same time there is huge profit as min is negative value**

**Sales has huge outliers as mean is too big than median as the data is Right Skewed**

**there are 1871 rows represents Loss**

In [35]:
df[df['Profit'] < 0].shape

(1871, 25)

**922 rows represent a big discount**

In [37]:
df[df['Discount'] >= 0.5].shape

(922, 25)

**Outliers I cannot delete them as they are important for Buisness**

**Product Cateogries**

In [38]:
df['Category'] = df['Category'].str.strip().str.lower()
df['Sub-Category'] = df['Sub-Category'].str.strip().str.lower()

In [40]:
df.duplicated(subset=['Product Name']).sum()

np.int64(8144)

In [41]:
df[df.duplicated(subset=['Product Name'], keep=False)].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Time,Profit Margin,Year,Month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,0.1600,2016,11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,0.3000,2016,11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,0.4700,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,-0.4000,2015,10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,0.1125,2015,10

In [42]:
df[df['Product Name'] == df['Product Name'].iloc[0]]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Time,Profit Margin,Year,Month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,bookcases,Bush Somerset Collection Bookcase,261.960,2,0.00,41.9136,3,0.160000,2016,11
5399,5400,CA-2016-117681,2016-04-09,2016-04-14,Standard Class,HF-14995,Herbert Flentye,Consumer,United States,Los Angeles,...,bookcases,Bush Somerset Collection Bookcase,556.665,5,0.15,6.5490,5,0.011765,2016,4
8634,8635,CA-2017-159793,2017-08-25,2017-08-29,Standard Class,SV-20365,Seth Vernon,Consumer,United States,Philadelphia,...,bookcases,Bush Somerset Collection Bookcase,130.980,2,0.50,-89.0664,4,-0.680000,2017,8
9334,9335,CA-2017-110198,2017-05-01,2017-05-02,First Class,AG-10900,Arthur Gainer,Consumer,United States,Coral Springs,...,bookcases,Bush Somerset Collection Bookcase,314.352,3,0.20,-15.7176,1,-0.050000,2017,5

**Product Name is NOT a unique key,but order id is unique**

In [43]:
df['Sub-Category'].unique()

array(['bookcases', 'chairs', 'labels', 'tables', 'storage',
       'furnishings', 'art', 'phones', 'binders', 'appliances', 'paper',
       'accessories', 'envelopes', 'fasteners', 'supplies', 'machines',
       'copiers'], dtype=object)

In [44]:
df['Sub-Category'] = df['Sub-Category'].str.lower().str.strip()

In [45]:
df['Category'].isnull().sum()
df['Sub-Category'].isnull().sum()

np.int64(0)

**To explore our Categories and subcateogries**

In [46]:
df.groupby(['Category', 'Sub-Category']).size()

Category         Sub-Category
furniture        bookcases        228
                 chairs           617
                 furnishings      957
                 tables           319
office supplies  appliances       466
                 art              796
                 binders         1523
                 envelopes        254
                 fasteners        217
                 labels           364
                 paper           1370
                 storage          846
                 supplies         190
technology       accessories      775
                 copiers           68
                 machines         115
                 phones           889
dtype: int64

**Customer Segments**

In [48]:
df['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

**Segment_Corporate
Segment_Home Office
(Consumer  will be baseline)**

In [49]:
df = pd.get_dummies(df, columns=['Segment'], drop_first=True)

**Shipping Modes**

In [50]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [51]:
df['Ship Mode'] = df['Ship Mode'].str.strip().str.lower()

**Check Spelling**

In [52]:
df['Ship Mode'] = df['Ship Mode'].replace({
    'standard-class': 'standard class',
    'same day': 'same day'
})

In [53]:
df = pd.get_dummies(df, columns=['Ship Mode'], drop_first=True)

**Step1: Preprocessing is Finished**